server:
  port: 9000


spring:
  task:
    execution:
      pool:
        core-size: 9                           # 核心线程数
        max-size: 20                           # 最大线程数
        keep-alive: 60000                      # 最大空闲时间
        queue-capacity: 256                    # 最大队列长度
      thread-name-prefix: create_sudoku        # 线程名称前缀